#
#This is an example .ini file 
#


file="C:\Wordpro ROM 1.bin"
adr=$D000
len=$1000

#commands dont have to be on a seperate line!

file="C:\Wordpro ROM 2.bin",adr=$E000



#parameters can be in any order! 
#and if "adr" parameter is missing it continues from end of last image

file="C:\Wordpro ROM 3.bin",len=$1000, ofs=$0000 


#Dont forget to change the file paths, this is just an example